version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: deidb_postgres
    ports:
      - "7654:5432"  # Keeps teacher's setup
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=deidb
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage
      - ./backend/src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./backend/src/main/resources/db/populate.sql:/docker-entrypoint-initdb.d/2-populate.sql
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
